import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'
import Main from '@/components/main'
import Progres from '@/components/progres'
import Aboutus from '@/components/aboutus'
import Meal from '@/components/meal'
import Cooker from '@/components/cooker'
import Cards from '@/components/cards'
import Clients from '@/components/clients'
import Contact from '@/components/contact'
import Footer from '@/components/footer'
import Copyright from '@/components/copyright'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>

      <Navbar />
      <Main />
      <Progres />
      <Aboutus />
      <Meal />
      <Cooker />
      <Cards />
      <Clients />
      <Contact />
      <Footer />
      <Copyright />


      
    </>
  )
}
